spring.application.name=used-car-consultancy
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:file:./data/usedcar
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=20MB
usedcar.consultancy.name= Ram Used Cars
usedcar.consultancy.mobiles=
usedcar.admin1.username=Ram
usedcar.admin1.password=Ram123
usedcar.admin2.username=
usedcar.admin2.password=

spring.thumeleaf.cache=false

